# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://www.yello.ae/location/dubai")
    self.driver.set_window_size(1043, 708)
    self.driver.execute_script("window.scrollTo(0,265)")
    self.driver.execute_script("window.scrollTo(0,3103)")
    self.driver.execute_script("window.scrollTo(0,4159)")
    self.driver.execute_script("window.scrollTo(0,4526)")
    self.driver.find_element(By.LINK_TEXT, "→").click()
    self.driver.switch_to.frame(10)
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.XPATH, "//div[@id=\'dismiss-button\']/div/span").click()
  
